
name: TestBuild

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
    - uses: subosito/flutter-action@v1.3.2
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
